import { Config } from "./variables";

const config = new Config({
  url: "https://www.olx.uz/nedvizhimost/kvartiry/tashkent/?currency=UYE", // Замените на ваш URL
  ResultFileName: "links.json",
  directory: "./output",
  server: {
    host: "localhost",
    port: 3000,
  },
  browser: {
    headless: true,
  },
  chunks: {
    ai: {
      timeout: 10000,
      maxAttempts: 5,
      maxTokens: 2000,
      temperature: 0.8,
      topP: 1,
      frequencyPenalty: 0,
      presencePenalty: 0,
      processedFileName: "processed_data.json",
      leakedFileName: "processed_data_leaked.json",
      debugFileName: "debug_processed_data.json",
    },
    filter: {
      keywords: [
        new Set([
          "аренда",
          "сдаю",
          "сдача",
          "сдается",
          "сдаются",
          "сдаем",
          "сдавать",
          "сдам",
          "сдать",
          "арендую",
          "арендовал",
          "арендуется",
          "сдаю в аренду",
          "арендаа",
          "сдаа",
          "arenda",
          "sdaju",
          "sdacha",
          "sdaetsya",
          "sdaem",
          "sdavat'",
          "sdam",
          "sdat'",
          "arenduem",
          "arenduju",
          "arendoval",
          "arenduetsya",
          "sdaju v arendu",
          "lease",
          "leasing",
          "let",
          "lease out",
          "sublease",
          "renatl",
          "leasig",
          "loco",
          "locamus",
          "locare",
          "locatio conductio",
          "лоцатио",
          "локо",
          "локамус",
          "локаре",
          "лоцатио кондукцио",
          "иҷора",
          "иҷора медиҳам",
          "иҷора мегирам",
          "иҷора кардан",
          "ijora",
          "ijora medidam",
          "ijora megiram",
          "ijora kardan",
          "ijara",
          "ijara beraman",
          "ijara beramiz",
          "ijara qilmoq",
          "ижара",
          "ижара берам",
          "ижара берамиз",
          "ижара қиламан",
          "إيجار",
          "تأجير",
          "ايجار",
          "ijar",
          "ta'jir",
          "taajir",
          "сдаётся",
          "Сдаётся ",
          "ижарага берилади",
        ]),
      ],
      outputFile: "filtered_results.json",
    },
  },
});

export default config;
